name: Bug report
description: Create a report to help us improve Amplify Hosting
labels: ["bug", "pending-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Try to include as much information as you can.

        > For **Amplify CLI** issues, go [here](https://github.com/aws-amplify/amplify-cli/issues/new/choose)
        > For **Amplify Studio** issues, go [here](https://github.com/aws-amplify/amplify-adminui/issues/new/choose)

  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
          required: true
        - label: I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
          required: true
        - label: I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
          required: true
        - label: I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
          required: true
        - label: I have removed any sensitive information from my code snippets and submission.
          required: true

  - type: markdown
    attributes:
      value: |
        ## Amplify Environment
  - type: input
    attributes:
      label: App Id
      description: |
        ```
        Find the App Id in the last portion of your URL. For example:

        https://console.aws.amazon.com/amplify/home?region=<AWS-REGION>#/<APP-ID>

        OR

        Within the Amplify Console, navigate to App Settings -> General -> App Arn, and inspect the last portion of the identifier:

        arn:aws:amplify:AWS-REGION:accountId:apps/<APP-ID>
        ```
    validations:
      required: true

  - type: dropdown
    attributes:
      label: AWS Region
      multiple: false
      options:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
        - ap-south-1
        - ap-southeast-1
        - ap-southeast-2
        - ap-northeast-1
        - ap-northeast-2
        - ap-east-1
        - ca-central-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - eu-central-1
        - eu-south-1
        - eu-north-1
        - sa-east-1
        - me-south-1
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Amplify Hosting feature
      description: What [feature(s)](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html#amplify-console-features) is this about?
      multiple: true
      options:
        - Access control
        - Access logs
        - Backend builds
        - Build settings
        - CloudWatch metrics
        - CloudWatch alarms
        - Custom build image
        - Custom headers
        - Deployments
        - E2E Cypress tests
        - Environment variables
        - Frontend builds
        - Git providers
        - Manual deploys
        - Monorepo
        - Notifications
        - One click deploy
        - Performance mode
        - Public APIs
        - Redirects
        - Service role
        - SSR
        - Web previews
        - Webhooks
        - Not Applicable
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Details
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: |
        How can this bug be reproduced? Please walk us through it step by step. 
        Screenshots can be provided in the issue body below.

      placeholder: |
        1. 
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Build Settings
      description: |
        If applicable, please include relevant portions of your `amplify.yml`. 

        **Be sure to remove any sensitive data.**
      render: yaml

  - type: textarea
    attributes:
      label: Log output
      description: |
        For example, error messages, or stack traces.

        **Be sure to remove any sensitive data.**

      value: |
        <details>

        ```
        # Put your logs below this line


        ```

        </details>

  - type: textarea
    attributes:
      label: Additional information
      description: |
        If you have any additional information, workarounds, etc. for us, use the field below.

        Please note, you can attach screenshots or screen recordings here, by dragging and dropping files in the field below.
