name: 🚀 Feature request
description: Have an idea for the AWS Amplify Hosting team? Submit a request.
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: "NOTE: This repository only accepts new feature requests for AWS Amplify Hosting. For technical support, we encourage you to open a case with [AWS technical support](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case) if you have AWS support plan. If you do not have an active AWS support plan, we encourage you to leverage our Amplify community [Discord server](https://discord.gg/amplify) where community members and staff try to help each other with Amplify."

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this questionaire! Try to include as much information as you can.

        > For **Amplify CLI** issues, go [here](https://github.com/aws-amplify/amplify-cli/issues/new/choose)
        > For **Amplify Studio** issues, go [here](https://github.com/aws-amplify/amplify-adminui/issues/new/choose)

  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
          required: true
        - label: I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
          required: true
        - label: I have removed any sensitive information from my code snippets and submission.
          required: true

  - type: dropdown
    attributes:
      label: Amplify Hosting feature
      description: What [feature(s)](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html#amplify-console-features) is this about?
      multiple: true
      options:
        - Access control
        - Access logs
        - Backend builds
        - Build settings
        - CloudWatch metrics
        - CloudWatch alarms
        - Custom build image
        - Custom headers
        - Deployments
        - E2E Cypress tests
        - Environment variables
        - Frontend builds
        - Git providers
        - Manual deploys
        - Monorepo
        - Notifications
        - One click deploy
        - Performance mode
        - Public APIs
        - Redirects
        - Service role
        - SSR
        - Web previews
        - Webhooks
        - Not Applicable
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Is your feature request related to a problem? Please describe:"
      description: |
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe how you'd like this feature to work"
      description: |
        A clear and concise description of what you want to happen.

        Add any context or screenshots about the feature request here.
    validations:
      required: true
